name: pe_icp_module
services:
  pe_icp_module:
    container_name: pe_icp_module
    image: ghcr.io/ad-sdl/pe_icp_module
    build:
      context: .
      tags:
        - ghcr.io/ad-sdl/pe_icp_module:latest
        - ghcr.io/ad-sdl/pe_icp_module:dev
    volumes:
      - ./src:/home/app/pe_icp_module/src
      - ./tests:/home/app/pe_icp_module/tests
    command: python -m pe_icp_module --port 2000
    ports:
      - 2000:2000
#####################
# WEI Core Services #
#####################
  pe_icp_wei_server:
    image: ghcr.io/ad-sdl/wei
    container_name: wei_server
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./workcells:/workcell_defs
    command: python3 -m wei.server --workcell /workcell_defs/test.workcell.yaml
    depends_on:
      - wei_redis
    profiles: [wei]
  pe_icp_wei_engine:
    image: ghcr.io/ad-sdl/wei
    container_name: wei_engine
    volumes:
      - ./workcells:/workcell_defs
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    command: python3 -m wei.engine --workcell /workcell_defs/test.workcell.yaml
    depends_on:
      - wei_redis
      - wei_server
    profiles: [wei]
  pe_icp_wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    profiles: [wei]
